### ISSUE TITLE
Add Solidity Random Number Implementations

### ISSUE THREAD

**Issue by slackenobi** [slackenobi/solidity-mocks#1]
### **Tasks**

- [ ] Add methods using Provable/Random.org

- [ ] Add methods using Provable/RandomDS-Ledger

- [ ] Create implementations that utilize Provable verifiable proofs

- [ ] Document with README files
---
* **Idea: Create a top-level Oracles folder for implementations of Provable other than TRNG and perhaps place `/random-numbers` under that rather than separate to avoid merging in the future**

**STRUCTURE:**
```
solidity-mocks/
     |
     --> Auth-Ownership/
     |        |
     |        --> ... subfolders
     --> Oracles
              |
              --> random-numbers <<<<<
              |
              --> ... other APIs
```
